%%{init: {'theme':'dark'}}%%
zenuml
    // detect_language
    path.extension()
    Some()
    Some()
    Some()
    // get_parser
    Box.new()
    Box.new()
    Box.new()
    // get_emitter
    Box.new()
    Box.new()
    Box.new()
    Box.new()
    // run
    CodeModel.new()
    path.is_file()
    parse_single_file(path, language) {
        language.or_else()
        parse.detect_language(path) {
            path.extension()
            Some()
            Some()
            Some()
        }
        std::fs.read_to_string(path)
        parse.get_parser(lang) {
            Box.new()
            Box.new()
            Box.new()
        }
        parser.parse_file(path, source)
    }
    merged.merge(model)
    path.is_dir()
    WalkDir.new(path)
    e.ok()
    e.file_type()
    entry.path()
    Some(l)
    parse.detect_language(file_path)
    parse_single_file(file_path)
    Some(lang)
    merged.merge(model)
    emit.get_emitter(diagram_type) {
        Box.new()
        Box.new()
        Box.new()
        Box.new()
    }
    Ok()
    emitter.emit(merged, theme)
